name: "[Docs] Build Only"

on:
  push:
    branches:
      - "**"

jobs:
  github-pages:
    strategy:
      matrix:
        scala: [ "2.13.11" ]
        java: [ "adopt@1.8" ]
        ruby: [ "2.6.3" ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Jekyll
        run: |
          gem install sass
          gem install jekyll -v 4.0.0

      - name: Build doc site
        run: |
          sbt --client ++${{ matrix.scala }} "docs/makeMicrosite"
